CREATE DATABASE lap2
GO

USE lap2

DROP DATABASE lap2

CREATE TABLE Phongban(
MaPB VARCHAR(7) PRIMARY KEY,
TenPB NVARCHAR(50),
)

CREATE TABLE Nhanvien(
MaNV VARCHAR(7) PRIMARY KEY,
TenNV NVARCHAR(50),
Ngaysinh DATETIME CHECK(ngaysinh < GETDATE()),
SoCMND CHAR(9)  CHECK (ISNUMERIC(SoCMND)=1),
Gioitinh char(1) check(gioitinh not like '[MF]' ) DEFAULT 'M',
Diachi NVARCHAR(100),
Ngayvaolam DATETIME CHECK( year() > 20),
MaPB VARCHAR(7)
CONSTRAINT fk FOREIGN KEY(MaPB) REFERENCES Phongban(MaPB)
)

CREATE TABLE LuongDA(
MaDA VARCHAR(8) PRIMARY KEY,
Ngaynhan DATETIME not null DEFAULT GETDATE(),
Sotien MONEY CHECK(Sotien > 0),
)

ALTER TABLE LuongDA
ADD CONSTRAINT PK_LuongDA PRIMARY KEY (MaNV),
CONSTRAINT fk FOREIGN KEY(MaNV) REFERENCES Nhanvien(MaNV);