CREATE DATABASE MSSQL_04
GO

USE MSSQL_04
GO

DROP DATABASE MSSQL_04
GO


CREATE TABLE SANPHAM(
MASANPHAM NVARCHAR(30) NOT NULL,
NGAYSANXUAT DATETIME,
ID_LSP INT PRIMARY KEY,
)

CREATE TABLE LOAI_SP(
MALOAISP NVARCHAR(20),
TENLOAISANPHAM VARCHAR(30),
ID_NV INT PRIMARY KEY,
ID_LSP INT,
CONSTRAINT FK FOREIGN KEY(ID_LSP) REFERENCES SANPHAM(ID_LSP) ON DELETE CASCADE,
)

CREATE TABLE NHANVIEN(
MANHANVIEN NVARCHAR(20),
TENNV NVARCHAR(30),
ID_NV INT,
CONSTRAINT FL FOREIGN KEY(ID_NV) REFERENCES LOAI_SP(ID_NV) ON DELETE CASCADE,
)

INSERT INTO SANPHAM(MASANPHAM,NGAYSANXUAT,ID_LSP) VALUES('Z37111111',12/12/09,1);
INSERT INTO LOAI_SP(MALOAISP,TENLOAISANPHAM,ID_NV,ID_LSP) VALUES('Z37E','MAYTINH37',01,1);
INSERT INTO NHANVIEN(MANHANVIEN,TENNV,ID_NV)VALUES(987688,'NGUYENVANA',01);

SELECT * FROM LOAI_SP
ORDER BY TENLOAISANPHAM

SELECT * FROM NhanVien
ORDER BY TENNV DESC

SELECT MALOAISP FROM LOAI_SP WHERE MALOAISP = 'Z37E'

SELECT MASANPHAM FROM SanPham  WHERE ID_LSP
IN
(SELECT ID_LSP FROM LOAI_SP WHERE ID_LSP
IN 
(SELECT MALOAISP FROM NHANVIEN WHERE Manhanvien
IN
(SELECT MANHANVIEN FROM NhanVien WHERE TENNV = 'Nguyen Van An'))) ORDER BY MASANPHAM DESC
